const PACKAGES = [
  "CSV",
  "DataFrames",
  "Dates",
  "Distributed",
  "FileIO",
  "GLM",
  "GZip",
  "Genie",
  "GenieCache",
  "GenieCacheFileCache",
  "HTTP",
  "Humanize",
  "Inflector",
  "Logging",
  "OrderedCollections",
  "SearchLight",
  "SearchLightSQLite",
  # "Stipple",
  # "StipplePlotly",
  # "StippleUI",
  "SwagUI",
  "SwaggerMarkdown",
  "TOML"
]